import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:yinwei_player/bridge/mock_engine.dart';
import 'package:yinwei_player/models/spatial_params.dart';
import 'package:yinwei_player/runtime/island_spatial_controls.dart';
import 'package:yinwei_player/screens/player_screen.dart';
import 'package:yinwei_player/state/engine_controller.dart';
import 'package:yinwei_player/state/window_mode_controller.dart';
import 'package:yinwei_player/widgets/island_spatial_controller.dart';
import 'package:yinwei_player/widgets/spatial_workspace.dart';
import 'package:yinwei_player/widgets/position_sidebar.dart';
import 'fake_window_chrome.dart';

void main() {
  testWidgets('real PlayerScreen Point and Array edits survive Full/Island in both directions', (tester) async {
    final engine = EngineController(engine: MockEngine());
    final window = WindowModeController(chrome: FakeWindowChrome());
    await tester.binding.setSurfaceSize(const Size(1440,900));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    await tester.pumpWidget(MaterialApp(home: PlayerScreen(controller: engine, windowMode: window)));
    await tester.pump();
    final initial = tester.widget<SpatialWorkspace>(find.byType(SpatialWorkspace)).sceneSnapshot!;
    final rev = initial['revision'];
    await window.enterIsland(); await window.expandIsland();
    window.setMiniOpen(true);
    await tester.pump();
    expect(find.byType(IslandSpatialController), findsOneWidget);
    var pad = tester.getRect(find.byKey(const ValueKey('mini-spatial-pad')));
    await tester.tapAt(pad.topLeft + const Offset(110, 58.5));
    await tester.pump();
    expect(engine.params.azimuthDeg, closeTo(0, 1e-7));
    expect(engine.params.distanceM, closeTo(2, 1e-7));
    await window.enterFull(); await tester.pump();
    var workspace = tester.widget<SpatialWorkspace>(find.byType(SpatialWorkspace));
    expect(workspace.sceneSnapshot!['revision'], rev + 1);
    expect(IslandPointIntent.pose(workspace.sceneSnapshot!).distanceM, closeTo(2, 1e-7));
    // Full inspector uses the same authority callback as ordinary UI controls.
    final inspector = tester.widget<PositionSidebar>(find.byType(PositionSidebar));
    inspector.onChanged(engine.params.copy()..azimuthDeg = -60..distanceM = 3);
    await tester.pump();
    await window.enterIsland(); await window.expandIsland(); window.setMiniOpen(true);
    await tester.pump();
    expect(find.text('-60°'), findsOneWidget);
    expect(find.text('3.00 m'), findsOneWidget);
    await tester.tap(find.byKey(const ValueKey('island-context-Stereo 2.0')));
    await tester.pump(); await tester.pump(const Duration(milliseconds: 40));
    window.setMiniOpen(true); await tester.pump();
    expect(find.byKey(const ValueKey('mini-speaker-handle-0')), findsOneWidget);
    expect(find.byKey(const ValueKey('mini-point-handle')), findsNothing);
    pad = tester.getRect(find.byKey(const ValueKey('mini-spatial-pad')));
    final rightBefore = engine.array.speakers[1].azimuthDeg;
    await tester.tapAt(pad.topLeft + const Offset(45, 102)); await tester.pump();
    expect(engine.array.speakers[0].azimuthDeg, closeTo(-90, 1e-7));
    expect(engine.array.speakers[1].azimuthDeg, rightBefore);
    await tester.tap(find.byKey(const ValueKey('mini-speaker-1'))); await tester.pump();
    await tester.tapAt(pad.topLeft + const Offset(175,102)); await tester.pump();
    expect(engine.array.speakers[1].azimuthDeg, closeTo(90, 1e-7));
    final l = engine.array.speakers[0].copy();
    await tester.tap(find.byKey(const ValueKey('mini-link'))); await tester.pump();
    final before = engine.array.copy();
    final slider = tester.widget<Slider>(find.byKey(const ValueKey('mini-elevation')));
    slider.onChanged!(25); await tester.pump();
    expect(engine.array.speakers[0].elevationDeg, closeTo(before.speakers[0].elevationDeg + 25, 1e-7));
    expect(engine.array.speakers[1].elevationDeg, 25);
    expect(engine.array.speakers[0].distanceM, engine.array.speakers[1].distanceM);
    await window.enterFull(); await tester.pump();
    workspace = tester.widget<SpatialWorkspace>(find.byType(SpatialWorkspace));
    expect(workspace.sceneSnapshot!['revision'], rev + 2);
    expect(workspace.arraySpeakers![0].azimuthDeg, l.azimuthDeg);
    expect(workspace.arraySpeakers![1].elevationDeg, 25);
    final fullInspector = tester.widget<PositionSidebar>(find.byType(PositionSidebar));
    final changed = engine.array.copy()..setAllDistance(2.75);
    fullInspector.onArrayChanged!(changed); await tester.pump();
    await window.enterIsland(); await window.expandIsland(); window.setMiniOpen(true); await tester.pump();
    expect(find.text('2.75 m'), findsOneWidget);
    await tester.tap(find.byKey(const ValueKey('mini-add-speaker')));
    await tester.pump();
    expect(engine.array.speakers.length, 3);
    expect(engine.array.speakers[2].feed, SpeakerFeed.mid);
    expect(engine.array.selectedIndex, 2);
    await window.enterFull();
    await tester.pump();
    workspace = tester.widget<SpatialWorkspace>(find.byType(SpatialWorkspace));
    expect(workspace.arraySpeakers!.length, 3);
    expect(find.text('3'), findsOneWidget);
    await window.enterIsland();
    await window.expandIsland();
    window.setMiniOpen(true);
    await tester.pump();
    expect(find.byKey(const ValueKey('mini-speaker-handle-2')), findsOneWidget);
    expect(find.byKey(const ValueKey('mini-remove-speaker')), findsOneWidget);
    await tester.tap(find.byKey(const ValueKey('island-context-Point'))); await tester.pump();
    window.setMiniOpen(true); await tester.pump();
    expect(find.text('-60°'), findsOneWidget);
    expect(find.text('3.00 m'), findsOneWidget);
    await window.enterFull(); await tester.pump();
    expect(tester.widget<SpatialWorkspace>(find.byType(SpatialWorkspace)).sceneSnapshot!['revision'], rev + 2);
    expect(engine.array.speakers[1].distanceM, 2.75);
    expect(tester.takeException(), isNull);
    await tester.pump(const Duration(milliseconds: 50));
    await tester.pumpWidget(const SizedBox());
    window.dispose(); engine.dispose();
  });
}
