#!/usr/bin/env bash
# Build spatial_core as an iOS static library and wrap it in an xcframework
# for the Flutter Runner. Does not modify DSP sources or C ABI signatures.
#
# Usage:
#   ./yinwei/tools/build_native_ios.sh
#   ./yinwei/tools/build_native_ios.sh device
#   ./yinwei/tools/build_native_ios.sh sim
#   ./yinwei/tools/build_native_ios.sh all   # default
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MODE="${1:-all}"
DEVICE_TARGET="aarch64-apple-ios"
SIM_TARGET="aarch64-apple-ios-sim"
OUT_DIR="$ROOT/apps/yinwei_player/ios/Native"
XCFRAMEWORK="$OUT_DIR/libspatial_core.xcframework"
REQUIRED_SYMBOLS=(
  yinwei_last_error
  yinwei_open
  yinwei_set_params
  yinwei_get_params
  yinwei_play
  yinwei_pause
  yinwei_current_azimuth_deg
  yinwei_current_elevation_deg
  yinwei_dispose
)

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

if [[ "$(uname -s)" != "Darwin" ]]; then
  fail "build_native_ios.sh must run on macOS with Xcode. This host is $(uname -s)."
fi

command -v xcodebuild >/dev/null 2>&1 || fail "xcodebuild not found. Install Xcode."
command -v rustup >/dev/null 2>&1 || fail "rustup not found."
command -v cargo >/dev/null 2>&1 || fail "cargo not found."
command -v xcrun >/dev/null 2>&1 || fail "xcrun not found."

rust_llvm_nm() {
  local sysroot host
  sysroot="$(rustc --print sysroot 2>/dev/null || true)"
  host="$(rustc -vV 2>/dev/null | awk '/^host:/{print $2}')"
  if [[ -n "$sysroot" && -n "$host" && -x "$sysroot/lib/rustlib/$host/bin/llvm-nm" ]]; then
    echo "$sysroot/lib/rustlib/$host/bin/llvm-nm"
  fi
}

# Apple nm from Xcode 26 cannot read object files produced by Rust 1.98+
# (LLVM 22 attribute kind 105). Prefer rustup's llvm-nm.
archive_exports() {
  local archive="$1"
  local llvm_nm
  llvm_nm="$(rust_llvm_nm)"
  if [[ -n "$llvm_nm" ]]; then
    "$llvm_nm" --defined-only -g "$archive" 2>/dev/null && return 0
  fi
  if command -v nm >/dev/null 2>&1; then
    nm -gU "$archive" 2>/dev/null && return 0
    nm -g "$archive" 2>/dev/null && return 0
  fi
  strings "$archive" 2>/dev/null
}

need_target() {
  local t="$1"
  if ! rustup target list --installed | grep -qx "$t"; then
    fail "Rust target $t is not installed. Run: rustup target add $t"
  fi
}

verify_archive() {
  local archive="$1"
  [[ -f "$archive" ]] || fail "missing archive: $archive"
  local exports
  exports="$(archive_exports "$archive")"
  local missing=()
  local sym
  for sym in "${REQUIRED_SYMBOLS[@]}"; do
    if ! grep -q "$sym" <<<"$exports"; then
      missing+=("$sym")
    fi
  done
  if ((${#missing[@]} > 0)); then
    fail "archive missing yinwei_* symbols (${missing[*]}): $archive"
  fi
  echo "Symbols OK -> $archive"
}

build_target() {
  local target="$1"
  echo "==> cargo build -p spatial_core --release --target $target --features realtime"
  (
    cd "$ROOT"
    cargo build -p spatial_core --release --target "$target" --features realtime
  )
  local archive="$ROOT/target/$target/release/libspatial_core.a"
  verify_archive "$archive"
  echo "ARTIFACT $archive"
}

mkdir -p "$OUT_DIR"

case "$MODE" in
  device)
    need_target "$DEVICE_TARGET"
    build_target "$DEVICE_TARGET"
    ;;
  sim)
    need_target "$SIM_TARGET"
    build_target "$SIM_TARGET"
    ;;
  all)
    need_target "$DEVICE_TARGET"
    need_target "$SIM_TARGET"
    build_target "$DEVICE_TARGET"
    build_target "$SIM_TARGET"
    ;;
  *)
    fail "unknown mode '$MODE' (use device|sim|all)"
    ;;
esac

DEVICE_A="$ROOT/target/$DEVICE_TARGET/release/libspatial_core.a"
SIM_A="$ROOT/target/$SIM_TARGET/release/libspatial_core.a"

rm -rf "$XCFRAMEWORK"
if [[ -f "$DEVICE_A" && -f "$SIM_A" ]]; then
  xcodebuild -create-xcframework \
    -library "$DEVICE_A" \
    -library "$SIM_A" \
    -output "$XCFRAMEWORK"
elif [[ -f "$DEVICE_A" ]]; then
  xcodebuild -create-xcframework -library "$DEVICE_A" -output "$XCFRAMEWORK"
elif [[ -f "$SIM_A" ]]; then
  xcodebuild -create-xcframework -library "$SIM_A" -output "$XCFRAMEWORK"
else
  fail "no libspatial_core.a produced"
fi

FORCE_LOAD="$ROOT/apps/yinwei_player/ios/Flutter/spatial_core_force_load.xcconfig"
# Appended via Runner OTHER_LDFLAGS = $(inherited) $(SPATIAL_CORE_FORCE_LDFLAGS).
# Do not assign OTHER_LDFLAGS here: SDK-conditional OTHER_LDFLAGS in a nested
# include replaces Flutter's flags and is also dropped by unsigned xcodebuild.
KEEP_SYMS="-u _yinwei_last_error -u _yinwei_open -u _yinwei_set_params -u _yinwei_play -u _yinwei_current_azimuth_deg -u _yinwei_dispose"
COREAUDIO_LIBS="-framework AVFoundation -framework AudioToolbox -framework CoreAudio -framework Accelerate -lc++"
{
  echo "// Generated by tools/build_native_ios.sh — do not edit."
  if [[ -f "$DEVICE_A" ]]; then
    echo "SPATIAL_CORE_FORCE_LDFLAGS[sdk=iphoneos*] = $COREAUDIO_LIBS -force_load $DEVICE_A $KEEP_SYMS"
  fi
  if [[ -f "$SIM_A" ]]; then
    echo "SPATIAL_CORE_FORCE_LDFLAGS[sdk=iphonesimulator*] = $COREAUDIO_LIBS -force_load $SIM_A $KEEP_SYMS"
  fi
} > "$FORCE_LOAD"
echo "ARTIFACT $FORCE_LOAD"
echo "ARTIFACT $XCFRAMEWORK"
echo "Done. Runner force-loads spatial_core. Do not link it into the App Clip until size is measured."
